### PR TITLE
Resized "icon set" as the default ones were too big on the dock in fashion mode ... out of proportion !!!

### PR DESCRIPTION
**Pull request by aiamuzz**
@sonichy ...

FYI ... this is my first ever fork and attempt to push/merge commits to a project ... so bear with on any shortcomings ...

This is what i have attempted to do ...

1. I have created a folder `iconset2` and added the resized icons (you default icon set as is but with reworked size and proportions) ... would it be possible for you to use this new resized icon set and release a new version so i can test it for the right size and proportions ?

2. I have created my own icon set and added them to `iconset3` ... I was hoping you could provide an option in your plugin to choose different icon set and hence organized them into a separate folder.

3. If you are willing to attempt, to accommodate the option, to let the user choose their icon set and the segregation of icon sets in separate folders is the correct way forward then i guess your default icons need to be moved to a separate folder hence the `iconset1` folder which houses your default icon set ... once you create the option to choose from multiple icon sets the same can be deleted from the `icons` folder as they will be duplicates of `iconset1` ...

PS : i am not a coder so how this will need to be done is up to you ... you can make necessary corrections as far as organizing the various icon sets as per your coding requirements.

### CODE REVIEW

**Comment by sonichy** [comment]
Because weather API will change frequently, and I am a beginner, not clear what you have changed.
So, I will not merge, If yours are better, they can install your branch.
Change icon theme, I do not know how to deal with now.

**Comment by aiamuzz** [comment]
@sonichy  ...

oh ... ok ...

hahahaha ... great ... even i am a beginner at pulling and pushing commits ... this is my first attempt at it ...

Can you atleast tell me the exact steps on how to compile and install this plugin ?

I'll try to compile my forked version and test it ...

**Comment by aiamuzz** [comment]
i basically want to know how to generate/package the file `libHTYWeather.so` ... if you can tell me the exact sequence of steps i can try to compile my own branch and test it out ...

**Comment by sonichy** [comment]
sudo apt install dde-dock-dev qt5-default.
Install Qt Creator in software store.

**Comment by aiamuzz** [comment]
> sudo apt install dde-dock-dev qt5-default.
> Install Qt Creator in software store.
> 
> 

ok ... i have installed them ... now what do i do ?

**Comment by CareF** [comment]
@aiamuzz 
Actually, if you want a simple solution, you don't have to use qt creator, which is a heavy IDE. 
Try following command (assuming you are already in the source code directory): 

```
mkdir build
cd build
qmake ..
make
```

(The first two are optional. They help to separate build result and source code)

And if you want to install/uninstall what's built, run `sudo make install` / `sudo make uninstall` . 
Restart dde-dock to see the result: 
`pkill dde-dock; dde-dock`

**Comment by sonichy** [comment]
open *.pro , my god.

**Comment by aiamuzz** [comment]
> open *.pro , my god.

sorry did not understand @sonichy ...

@CareF ... thank your suggestion worked ... now i have the plugin with my own custom icons ...

deepinscreenshot_select-area_20190101202310
deepinscreenshot_select-area_20190101204841
deepinscreenshot_select-area_20190101204637

**Comment by aiamuzz** [comment]
@sonichy ... if you are interested in this icons let me know ...

You should try to provide an option in your weather plugin to have icon themes ... that way you can have your default ... as well as other icons design ... i would certainly use the gray ones as it suits my desktop / dock better ... your default icon theme is too brightly colored for my liking ...

**Comment by sonichy** [comment]
Think deeply ......

**Comment by CareF** [comment]
@aiamuzz If you permit, I think I can make a fork and add your icons as a theme option. Do you mind giving me a name for the theme? 

@sonichy Thank you for the plugin! 
谢谢你的插件. 因为你没有标注许可, 但使用了 deepin 的 API 代码, 我猜默认用 GPLv3? 除非你不同意不然的话我是不是可以按照 GPLv3 的规则修改你的代码?

**Comment by sonichy** [comment]
版权我是真心不懂，你只要像写论文那样，注明出处就行。
我有一个长远的构想，使用算法自动计算代码的相似度，以及父代子代孙代......

**Comment by aiamuzz** [comment]
@CareF ... that's great ... i have some tweaks to be made to my icons set ... while i do that ...
you go ahead and fork it ... let me know once you've done so ...

i'll fork your fork and i'll push commits(as this is a learning experience) ... i'll think of a theme name too by then ... :)

**Comment by sonichy** [comment]
Good news: support user icon path !
alt

**Pull request closed without merging**
